[theme]
primaryColor = "#007FFF"
backgroundColor = "#082567"
secondaryBackgroundColor = "#2A52BE"
textColor = "#FAFAFA"
font = "sans serif"

[custom_css]
css = """
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=Playfair+Display:wght@400;500;600;700&display=swap');

/* Base styles */
body {
    font-family: 'Roboto', sans-serif;
    line-height: 1.6;
    color: #FAFAFA;
    background-color: #082567;
}

h1, h2, h3, h4, h5, h6 {
    font-family: 'Playfair Display', serif;
    color: #FAFAFA;
    letter-spacing: -0.02em;
}

/* Enhanced Sidebar styling with double-box glass effect */
section[data-testid="stSidebar"] {
    background: linear-gradient(180deg, rgba(18, 10, 143, 0.7) 0%, rgba(8, 37, 103, 0.8) 100%);
    backdrop-filter: blur(20px);
    border-right: 1px solid rgba(255, 255, 255, 0.1);
    box-shadow: 2px 0 20px rgba(0, 0, 0, 0.2);
    min-width: 300px !important;
}

section[data-testid="stSidebar"] > div {
    padding: 2rem 1rem;
    background: linear-gradient(135deg, rgba(255, 255, 255, 0.05) 0%, rgba(255, 255, 255, 0.02) 100%);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.05);
    border-radius: 16px;
    margin: 1rem;
    box-shadow: 
        0 4px 12px rgba(0, 0, 0, 0.1),
        inset 0 0 20px rgba(255, 255, 255, 0.05);
}

/* Sidebar Navigation Styling */
section[data-testid="stSidebar"] [data-testid="stRadio"] {
    background: rgba(255, 255, 255, 0.03);
    padding: 1rem;
    border-radius: 12px;
    border: 1px solid rgba(255, 255, 255, 0.05);
}

section[data-testid="stSidebar"] [role="radiogroup"] {
    gap: 0.5rem !important;
    display: flex;
    flex-direction: column;
}

section[data-testid="stSidebar"] [data-testid="stRadio"] label {
    background: rgba(42, 82, 190, 0.2);
    border: 1px solid rgba(255, 255, 255, 0.05);
    border-radius: 8px;
    padding: 0.8rem 1rem;
    cursor: pointer;
    transition: all 0.3s ease;
    backdrop-filter: blur(5px);
}

section[data-testid="stSidebar"] [data-testid="stRadio"] label:hover {
    background: rgba(42, 82, 190, 0.3);
    transform: translateX(5px);
}

section[data-testid="stSidebar"] [data-testid="stRadio"] label[data-checked="true"] {
    background: linear-gradient(135deg, rgba(0, 127, 255, 0.3) 0%, rgba(0, 127, 255, 0.2) 100%);
    border-color: rgba(255, 255, 255, 0.1);
    transform: translateX(5px);
    box-shadow: 
        0 4px 12px rgba(0, 0, 0, 0.1),
        inset 0 0 20px rgba(255, 255, 255, 0.05);
}

/* Sidebar Headers */
section[data-testid="stSidebar"] h1 {
    color: #FFFFFF;
    font-size: 1.5rem;
    margin-bottom: 2rem;
    padding-bottom: 1rem;
    border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

section[data-testid="stSidebar"] .block-container {
    background: transparent;
}

/* Sidebar Sections */
section[data-testid="stSidebar"] .stMarkdown {
    background: rgba(255, 255, 255, 0.05);
    padding: 1rem;
    border-radius: 12px;
    margin: 0.5rem 0;
    backdrop-filter: blur(5px);
    border: 1px solid rgba(255, 255, 255, 0.05);
    transition: all 0.3s ease;
}

section[data-testid="stSidebar"] .stMarkdown:hover {
    background: rgba(255, 255, 255, 0.08);
    transform: translateY(-2px);
}

/* Sidebar Upload Area */
section[data-testid="stSidebar"] [data-testid="stFileUploader"] {
    background: rgba(42, 82, 190, 0.2);
    padding: 1.5rem;
    border-radius: 12px;
    border: 1px dashed rgba(255, 255, 255, 0.2);
    margin: 1rem 0;
    transition: all 0.3s ease;
}

section[data-testid="stSidebar"] [data-testid="stFileUploader"]:hover {
    background: rgba(42, 82, 190, 0.3);
    border-color: rgba(255, 255, 255, 0.3);
}

/* Sidebar Buttons */
section[data-testid="stSidebar"] .stButton button {
    width: 100%;
    margin: 0.5rem 0;
    background: linear-gradient(135deg, rgba(255, 75, 75, 0.9) 0%, rgba(255, 0, 0, 0.8) 100%);
    backdrop-filter: blur(5px);
}

/* Sidebar Divider */
section[data-testid="stSidebar"] hr {
    margin: 0.3rem 0;
    border: 0;
    height: 0.3px;
    background: linear-gradient(90deg, 
        rgba(255, 255, 255, 0) 0%, 
        rgba(255, 255, 255, 0.1) 50%, 
        rgba(255, 255, 255, 0) 100%
    );
}

/* Container Styling */
.main .block-container {
    background-color: #082567;
    padding: 2rem;
    border-radius: 12px;
    box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.3);
}

/* Chat Interface */
.stChatMessage {
    background-color: #2A52BE;
    color: #FAFAFA;
    border-radius: 12px;
    padding: 1.2rem;
    margin: 1rem 0;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    transition: transform 0.2s ease;
}

/* Tabs Styling (Commented out as tabs are replaced by sidebar navigation)
.stTabs {
    display: flex;
    justify-content: center;
    margin: 0 auto;
    max-width: 900px;
}

.stTabs [data-baseweb="tab-list"] {
    gap: 0.8rem;
    background-color: rgba(8, 37, 103, 0.8);
    padding: 0.8rem;
    border-radius: 20px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
    backdrop-filter: blur(10px);
    border: 1px solid rgba(255, 255, 255, 0.1);
    display: flex;
    justify-content: center;
    width: 100%;
}*/

/* Hide default elements */
#MainMenu {visibility: hidden !important;}
footer {visibility: hidden !important;}
header {visibility: hidden !important;}
/*

.stTabs [data-baseweb="tab"] {
    height: 45px;
    border-radius: 12px;
    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
    font-weight: 600;
    color: rgba(255, 255, 255, 0.8);
    padding: 0 1.5rem;
    display: flex;
    align-items: center;
    justify-content: center;
    border: 1px solid rgba(255, 255, 255, 0.05);
    background-color: rgba(42, 82, 190, 0.3);
}

.stTabs [data-baseweb="tab"]:hover {
    background-color: rgba(0, 127, 255, 0.2);
    transform: translateY(-2px);
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    color: #FFFFFF;
}

.stTabs [data-baseweb="tab"][aria-selected="true"] {
    background-color: #007FFF;
    color: #FFFFFF;
    box-shadow: 0 4px 12px rgba(0, 127, 255, 0.3);
    border: 1px solid rgba(255, 255, 255, 0.2);
    transform: translateY(-2px);
}*/

/* Interactive Elements */
.stButton button,
button[kind="primary"] {
    background-color:rgb(177, 35, 35);
    color: #FFFFFF;
    border-radius: 8px;
    padding: 0.6rem 1.2rem;
    font-weight: 500;
    border: none;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
    transition: all 0.2s ease;
}

.stButton button:hover,
button[kind="primary"]:hover {
    background-color:rgb(210, 25, 65);
    transform: translateY(-1px);
    box-shadow: 0 4px 6px rgba(4, 67, 161, 0.3);
}

/* Form Elements */
.stTextInput input,
.stTextArea textarea {
    background-color: #2A52BE;
    color: #FAFAFA;
    border: 1px solid #007FFF;
    border-radius: 8px;
}

.stTextInput input:focus,
.stTextArea textarea:focus {
    border-color: #007FFF;
    box-shadow: 0 0 0 1px #007FFF;
}

/* Responsive Design */
@media screen and (max-width: 768px) {
    .main .block-container {
        padding: 1rem;
    }
    
    .stChatMessage {
        padding: 1rem;
        margin: 0.5rem 0;
    }
    
    h1 { font-size: 1.5rem; }
    h2 { font-size: 1.2rem; }
}
"""